"""Generated Dockerfiles for apps that don't bring their own.

node / python / static get a sensible default image so simple apps need no
Dockerfile. `runtime: docker` apps use their own Dockerfile instead.
"""
from __future__ import annotations

NODE = """\
# Generated by Loom. App reads $PORT.
FROM node:22-alpine
WORKDIR /app
COPY . .
RUN if [ -f package-lock.json ]; then npm ci --omit=dev; \\
    elif [ -f package.json ]; then npm install --omit=dev; fi
EXPOSE {port}
CMD ["npm", "start"]
"""

PYTHON = """\
# Generated by Loom. App reads $PORT and is started via `python app.py`.
FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
EXPOSE {port}
CMD ["python", "app.py"]
"""

STATIC = """\
# Generated by Loom. Static files served by nginx on port 80.
FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
"""


def generate(runtime: str, port: int | None) -> str | None:
    """Return Dockerfile text for a generated runtime, or None for `docker`."""
    if runtime == "node":
        return NODE.format(port=port)
    if runtime == "python":
        return PYTHON.format(port=port)
    if runtime == "static":
        return STATIC
    return None  # docker: use the app's own Dockerfile
