"""The Traefik reverse-proxy: lifecycle, local TLS, network, and route files.

Routes are declared via files in proxy/dynamic that Traefik's file provider
watches. The Loom CLI writes one file per public app, so the route table stays
under Loom's control (the seed of the future Library).
"""
from __future__ import annotations

import os
import shutil

from . import dockercmd
from .config import Paths, paths
from .util import LoomError, info, ok, warn

PROXY_CONTAINER = "loom-proxy"
TLS_FILE = "tls.yml"


def _cert_paths(cfg: dict, p: Paths):
    base = cfg["base_domain"]
    return p.certs / f"{base}.pem", p.certs / f"{base}-key.pem"


def compose_env(cfg: dict) -> dict:
    env = dict(os.environ)
    env["LOOM_HTTP_PORT"] = str(cfg["http_port"])
    env["LOOM_HTTPS_PORT"] = str(cfg["https_port"])
    return env


def is_running() -> bool:
    return dockercmd.container_state(PROXY_CONTAINER) == "running"


def ensure_network(cfg: dict) -> None:
    dockercmd.network_ensure(cfg["network"])


def ensure_cert(cfg: dict) -> None:
    """Generate a local wildcard cert via mkcert and write Traefik's TLS config.

    Falls back to Traefik's self-signed default cert (browser warning) if mkcert
    is unavailable.
    """
    p = paths()
    p.certs.mkdir(parents=True, exist_ok=True)
    p.dynamic.mkdir(parents=True, exist_ok=True)
    cert, key = _cert_paths(cfg, p)
    base = cfg["base_domain"]

    if not (cert.exists() and key.exists()):
        mkcert = shutil.which("mkcert")
        if mkcert:
            info(f"generating local TLS cert for *.{base}")
            import subprocess

            subprocess.run(
                [mkcert, "-cert-file", str(cert), "-key-file", str(key),
                 f"*.{base}", base],
                check=True, capture_output=True, text=True,
            )
        else:
            warn("mkcert not found — Traefik will use a self-signed cert "
                 "(browsers will warn). Install mkcert for trusted HTTPS.")
            # Empty TLS config -> Traefik serves its built-in self-signed cert.
            (p.dynamic / TLS_FILE).write_text("{}\n")
            return

    (p.dynamic / TLS_FILE).write_text(
        "# Generated by Loom — local TLS for *.{base}.\n"
        "tls:\n"
        "  stores:\n"
        "    default:\n"
        "      defaultCertificate:\n"
        "        certFile: /certs/{base}.pem\n"
        "        keyFile: /certs/{base}-key.pem\n"
        "  certificates:\n"
        "    - certFile: /certs/{base}.pem\n"
        "      keyFile: /certs/{base}-key.pem\n".format(base=base)
    )


def up(cfg: dict) -> None:
    if not dockercmd.daemon_ok():
        raise LoomError("Docker daemon is not reachable. Is Docker / OrbStack running?")
    p = paths()
    if not p.compose_file.exists():
        raise LoomError(f"proxy compose file missing: {p.compose_file}")
    ensure_network(cfg)
    ensure_cert(cfg)
    dockercmd.run(
        ["compose", "-f", str(p.compose_file), "up", "-d"],
        capture=True, env=compose_env(cfg),
    )
    ok(f"proxy up (http :{cfg['http_port']}, https :{cfg['https_port']})")


def ensure(cfg: dict) -> None:
    """Bring the proxy up if it isn't already (idempotent)."""
    if is_running():
        ensure_network(cfg)
        return
    up(cfg)


def down(cfg: dict) -> None:
    p = paths()
    dockercmd.run(
        ["compose", "-f", str(p.compose_file), "down"],
        capture=True, env=compose_env(cfg), check=False,
    )
    ok("proxy down")


def status(cfg: dict) -> None:
    state = dockercmd.container_state(PROXY_CONTAINER)
    if state == "running":
        ok(f"proxy running (http :{cfg['http_port']}, https :{cfg['https_port']})")
        print(f"  dashboard: http://127.0.0.1:8080/dashboard/")
    elif state is None:
        warn("proxy not created — run `loom proxy up`")
    else:
        warn(f"proxy exists but is '{state}' — run `loom proxy up`")


# --- per-app route files (Traefik file provider) -------------------------------

def route_file(name: str):
    return paths().dynamic / f"app-{name}.yml"


def write_route(cfg: dict, name: str, container: str, service_port: int,
                middlewares: list[str] | None = None) -> None:
    paths().dynamic.mkdir(parents=True, exist_ok=True)
    # Local hostname always; public hostname too when a public domain is set, so
    # the external gateway can route <name>.<public_domain> to this app. Only
    # public/gated apps reach this function — private apps never get a route
    # file, so they are never matched on the public hostname (tier enforced here).
    hosts = [f"Host(`{name}.{cfg['base_domain']}`)"]
    public_domain = cfg.get("public_domain") or ""
    if public_domain:
        hosts.append(f"Host(`{name}.{public_domain}`)")
    rule = " || ".join(hosts)
    mw_lines = ""
    if middlewares:
        mw_lines = "      middlewares:\n" + "".join(
            f"        - {m}\n" for m in middlewares
        )
    content = (
        f"# Generated by Loom for app '{name}'. Do not edit by hand.\n"
        "http:\n"
        "  routers:\n"
        f"    {name}:\n"
        f'      rule: "{rule}"\n'
        "      entryPoints: [websecure]\n"
        f"      service: {name}\n"
        + mw_lines +
        "      tls: {}\n"
        "  services:\n"
        f"    {name}:\n"
        "      loadBalancer:\n"
        "        servers:\n"
        f'          - url: "http://{container}:{service_port}"\n'
    )
    route_file(name).write_text(content)


def remove_route(name: str) -> None:
    f = route_file(name)
    if f.exists():
        f.unlink()
